export const WEATHER_ACTION_TYPES = {
  FETCH_WEATHER_FORECAST_START: 'FETCH_WEATHER_FORECAST_START',
  FETCH_WEATHER_FORECAST_SUCCESS: 'FETCH_WEATHER_FORECAST_SUCCESS',
  FETCH_WEATHER_FORECAST_ERROR: 'FETCH_WEATHER_FORECAST_ERROR',

  FETCH_WEATHER_CURRENT_START: 'FETCH_WEATHER_CURRENT_START',
  FETCH_WEATHER_CURRENT_SUCCESS: 'FETCH_WEATHER_CURRENT_SUCCESS',
  FETCH_WEATHER_CURRENT_ERROR: 'FETCH_WEATHER_CURRENT_ERROR',
  TIME_FETCH_WEATHER: 'TIME_FETCH_WEATHER',
  TIME_FETCH_FORECAST: 'TIME_FETCH_FORECAST',
}