export const WIDGETS_ACTION_TYPES = {
  SET_FOOTER_WIDGETS: 'SET_FOOTER_WIDGETS',
  SET_DEFAULT_WIDGETS: 'SET_DEFAULT_WIDGETS',
  SET_ADDED_WIDGETS: 'SET_ADDED_WIDGETS',
  SET_MODAL_COMMON_INFO: 'SET_MODAL_COMMON_INFO',
}
