export const WIDGETS_ACTION_TYPES = {
  SET_WIDGETS_FOOTER: 'SET_WIDGETS_FOOTER',
  SET_WIDGETS_MAIN: 'SET_WIDGETS_MAIN',
  SET_ALL_SERVICE: 'SET_ALL_SERVICE',
  SET_ALL_SETTINGS: 'SET_ALL_SETTINGS',
  SET_RENDER_WIDGETS: 'SET_RENDER_WIDGETS',
  SET_MODAL_COMMON_INFO: 'SET_MODAL_COMMON_INFO',
}