export const SET_ACTION_SLEEP_MODE = {
  SET_ACTIVE_DOORBELL_SETTING: 'SET_ACTIVE_DOORBELL_SETTING',
  SET_ACTIVE_VISITOR_CALL_SETTING: 'SET_ACTIVE_VISITOR_CALL_SETTING',
  SET_SHOW_SLEEP_MODAL: 'SET_SHOW_SLEEP_MODAL',
  SET_SLEEP_MODE_TIMER: 'SET_SLEEP_MODE_TIMER',
}